version: '3'
services:
  tyamahori-mysql80:
    image: mysql:8.0
    container_name: tyamahori-mysql80
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_USER: tyamahori
      MYSQL_ROOT_PASSWORD: tyamahori
      MYSQL_PASSWORD: tyamahori
      MYSQL_DATABASE: tyamahori
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_RANDOM_ROOT_PASSWORD: tyamahori
      TZ: Asia/Tokyo